    <div style="text-align: center;">
        <a href="http://powet.tv/powetblog/tag/a-is-for/">A</a> | 
        <a href="http://powet.tv/powetblog/tag/b-is-for/">B</a> |
        <a href="http://powet.tv/powetblog/tag/c-is-for/">C</a> |
        <a href="http://powet.tv/powetblog/tag/d-is-for/">D</a> |
        <a href="http://powet.tv/powetblog/tag/e-is-for/">E</a> |
        <a href="http://powet.tv/powetblog/tag/f-is-for/">F</a> |
        <a href="http://powet.tv/powetblog/tag/g-is-for/">G</a> |
        <a href="http://powet.tv/powetblog/tag/h-is-for/">H</a> |
        <a href="http://powet.tv/powetblog/tag/i-is-for/">I</a> |
        <a href="http://powet.tv/powetblog/tag/j-is-for/">J</a> |
        <a href="http://powet.tv/powetblog/tag/k-is-for/">K</a> |
        <a href="http://powet.tv/powetblog/tag/l-is-for/">L</a> |
        <a href="http://powet.tv/powetblog/tag/m-is-for/">M</a> | 
        <a href="http://powet.tv/powetblog/tag/n-is-for/">N</a> |
        <a href="http://powet.tv/powetblog/tag/o-is-for/">O</a> |
        <a href="http://powet.tv/powetblog/tag/p-is-for/">P</a> |
        <a href="http://powet.tv/powetblog/tag/q-is-for/">Q</a> |
        <a href="http://powet.tv/powetblog/tag/r-is-for/">R</a> |
        <a href="http://powet.tv/powetblog/tag/s-is-for/">S</a> |
        <a href="http://powet.tv/powetblog/tag/t-is-for/">T</a> |
        <a href="http://powet.tv/powetblog/tag/u-is-for/">U</a> |
        <a href="http://powet.tv/powetblog/tag/v-is-for/">V</a> |
        <a href="http://powet.tv/powetblog/tag/w-is-for/">W</a> |
        <a href="http://powet.tv/powetblog/tag/x-is-for/">X</a> |
        <a href="http://powet.tv/powetblog/tag/y-is-for/">Y</a> |
        <a href="http://powet.tv/powetblog/tag/z-is-for/">Z</a>
    </div>